apiVersion: v1
kind: Namespace
metadata:
  name: sre-sentinel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: sre-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sentinel
          image: ghcr.io/islemazz/sre-sentinel
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SENTINEL_DB
              value: /tmp/incidents.db
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 192Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: sre-sentinel
spec:
  type: NodePort
  selector:
    app: sentinel
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

