apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 91.9.0
    helm:
      valuesObject:
        nodeExporter:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        alertmanager:
          alertmanagerSpec:
            resources:
              requests: {cpu: 20m, memory: 48Mi}
              limits: {memory: 128Mi}
        grafana:
          admin:
            existingSecret: grafana-admin
            userKey: admin-user
            passwordKey: admin-password
          resources:
            requests: {cpu: 50m, memory: 128Mi}
            limits: {memory: 384Mi}
        prometheus:
          prometheusSpec:
            retention: 3d
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            resources:
              requests: {cpu: 100m, memory: 400Mi}
              limits: {memory: 900Mi}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
