apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/islemazz/sre-sentinel-gitops.git
    targetRevision: main
    path: apps/sentinel
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-sentinel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
